### PR TITLE
add filter to extend restriction fields

### PR DESCRIPTION
**Pull request by omarkasem**
Add a new apply_filters to extend the restriction fields

### CODE REVIEW

**Comment by jack-arturo** [comment]
Following :)

**Comment by danieliser** [comment]
@omarkasem - Many apologies, I never even saw this, mainly as the plugin rarely got updated.

The new v2 UX is done in react anyways so this would have been a breaking change, but if you can tell me where you need to add fields to the new UX I can add react portals for you to use.

If so lets open a new issue as this is not mergeable in the new version unfortunately.

**Comment by jack-arturo** [comment]
@omarkasem We'll close this on our end for now, I think if we get a Content Control request I'll see if @danieliser can add it from his end with the new rules system.

**Comment by danieliser** [comment]
@verygoodplugins - That sounds perfectly suitable, the changes will be good prep as we move that same new rule engine into WP Popup Maker as well, which you also integrate with.

**Pull request closed without merging**
