### PR TITLE
Filter to override short-circuit of conditions

### PR DESCRIPTION
**Pull request by marklchaves**
Added logic to accept a short-circuit override filter.

If the filter returns **true**, then loop through all restrictions to see if there's at least 1 allowable restriction.

**Issue**: https://github.com/JunglePlugins/Content-Control/issues/49

## Test cases

1. Created 3 restrictions with 1 role and 1 post category each. Created a post with all three categories.
2. Created 3 posts. Each post has 1 category created in test case 1.
3. Created a post with a category that has no restrictions.
4. Created a post with a category that has a logged-out restriction.

## Usage

`add_filter( 'content_control_override_short_circuit', '__return_true' );`

### CODE REVIEW

**Comment by RedBlueBulb** [comment]
This is awesome - many thanks @marklchaves for actioning my feature request

**Comment by danieliser** [comment]
This was built into v2 & is either documented already or on the list to be, so I'm gonna close this.

**Comment by marklchaves** [comment]
> This was built into v2 & is either documented already or on the list to be, so I'm gonna close this.

Yep. This works in v2 beautifully. Thank you!

And it's documented.

https://contentcontrolplugin.com/docs/troubleshooting/basic-troubleshooting-guide/#h-4-my-top-restrictions-stop-or-short-circuit-ones-lower-in-the-restriction-list

**Comment by RedBlueBulb** [comment]
Many thanks @danieliser for v2. And many thanks @marklchaves for raising the feature request.

**Pull request closed without merging**
